#!/bin/python3
import sys
from collections import Counter

Q = int(input().strip())
for a0 in range(Q):
    n = int(input().strip())
    b = input().strip()
    d = Counter(b)
    u = d.pop('_',0)
    if 1 in d.values():
        print('NO')
    elif u:
        print('YES')
    elif b[0] == b[1] and all(b[i-1]==b[i] or b[i] == b[i+1] for i in range(1, n-1)) and b[-2] == b[-1]:
        print('YES')
    else:
        print('NO')
